import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const font = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark scroll-smooth">
      <body className={`${font.className} dark:bg-gray-900 dark:text-gray-200`}>
        <Navbar />
        <div className="container mx-auto md:max-w-5xl p-4 mt-5">
          {children}
        </div>
      </body>
    </html>
  );
}
